import { useEffect, useRef, useState } from 'react';
import { aggregate, date, methodLabel, money, request, statusLabels, upload, type Group, type Method, type Order, type Preview, type Product, type Selection } from './api';
import { Empty, Gallery, Lines, Media, OrderCard, Primary, Quantity, type Workspace } from './ui';
import { ChangeReview } from './seller';

export function Catalog({ products, context, open }: { products: Product[]; context: Workspace; open: (id: string) => void }) {
  return <><div className="page-title"><span className="eyebrow">CURATED FINDS</span><h1>Find something lovely</h1><p>Reserve at checkout. Pay externally. We’ll take care of the rest.</p></div>{products.length ? <div className="product-grid">{products.map(product => <article className="product-card" key={product.id}><button className="product-image" onClick={() => open(product.id)} aria-label={`View ${product.name}`}><img src={`/api/public-media/${product.images[0]}`} alt={product.name} loading="lazy" /></button><div className="product-copy"><button className="product-name" onClick={() => open(product.id)}>{product.name}</button><strong>{money(product.price, context.session.currency)}</strong><p className={product.available === 0 ? 'stock unavailable' : 'stock'}>{product.available > 0 ? `${product.available} available` : product.reserved > 0 ? 'Temporarily reserved' : 'Sold out'}</p><small>{product.reserved} reserved · {product.bought} bought</small></div></article>)}</div> : <Empty title="Something lovely is coming">The seller hasn’t published any products yet. Check back soon.</Empty>}</>;
}
export function ProductDetail({ product, context, quantity, setQuantity }: { product: Product; context: Workspace; quantity: number; setQuantity: (value: number) => void }) {
  const [selected, setSelected] = useState(Math.min(Math.max(quantity, 1), product.available));
  const [added, setAdded] = useState(false);
  return <><Gallery ids={product.images} token={context.session.token} name={product.name} publicImages /><div className="page-title"><span className="eyebrow">THE DETAILS</span><h1>{product.name}</h1><div className="large-price">{money(product.price, context.session.currency)}</div>{product.comment && <p className="preserve">{product.comment}</p>}</div><div className="stock-summary"><div><strong>{product.available}</strong><span>Available</span></div><div><strong>{product.reserved}</strong><span>Reserved</span></div><div><strong>{product.bought}</strong><span>Bought</span></div></div><section className="card"><div className="row"><label>Quantity for your cart</label><Quantity name={product.name} value={selected} max={product.available} onChange={value => { setSelected(value); setAdded(false); }} /></div><p className="muted">A cart does not hold stock. Availability and prices are checked again before you confirm an order.</p><Primary busy={context.busy} disabled={selected === 0 || selected > product.available} onClick={() => { setQuantity(selected); setAdded(true); }}>{quantity ? 'Update cart quantity' : 'Add to cart'}</Primary>{added && <p className="success-text" role="status">Cart updated. Open Cart to check out.</p>}</section></>;
}

export function SelectionEditor({ products, groups, context, initial, order, checkoutKey, onSelection, onDone }: { products: Product[]; groups: Group[]; context: Workspace; initial?: Record<string, number>; order?: Order; checkoutKey?: { current: { payload: string; key: string } | null }; onSelection?: (value: Record<string, number>) => void; onDone: (id: string) => void }) {
  const [quantities, setQuantities] = useState<Record<string, number>>(initial ?? Object.fromEntries(aggregate(order?.lines ?? []).map(item => [item.productId, item.quantity])));
  const [preview, setPreview] = useState<Preview | null>(null);
  const [method, setMethod] = useState<Method>('delivery');
  const [groupId, setGroupId] = useState('');
  const [note, setNote] = useState('');
  const localKey = useRef<{ payload: string; key: string } | null>(null);
  const key = checkoutKey ?? localKey;
  const requested = !!order && order.status !== 'awaiting_payment';
  const items: Selection = Object.entries(quantities).filter(([, quantity]) => quantity > 0).map(([productId, quantity]) => ({ productId, quantity }));
  const choices = [...products.filter(product => product.published), ...aggregate(order?.lines ?? []).filter(item => !products.some(product => product.id === item.productId)).map(item => ({ id: item.productId, name: order!.lines.find(line => line.product_id === item.productId)!.name, price: 0, available: 0, published: false }))];
  const update = (id: string, quantity: number) => {
    const next = { ...quantities, [id]: quantity }; setQuantities(next); setPreview(null); onSelection?.(next);
  };
  const selectedGroup = groups.find(group => group.id === groupId);
  const openGroups = groups.filter(group => group.state === 'open');
  const suggestedGroup = openGroups.reduce<Group | undefined>((latest, group) => !latest || new Date(group.created_at).getTime() > new Date(latest.created_at).getTime() ? group : latest, undefined);
  const retained = Object.fromEntries(aggregate(order?.lines ?? []).map(item => [item.productId, item.quantity]));
  const calculate = () => void context.run(async () => { setPreview(await request<Preview>('/orders/preview', context.session.token, { items, ...(order ? { orderId: order.id } : {}) })); });
  const accept = () => void context.run(async () => {
    if (!preview) return;
    if (order && !requested && items.length === 0) {
      if (!window.confirm('Cancel this unpaid order and release every held item?')) return false;
      const result = await request<Order>(`/orders/${order.id}/cancel`, context.session.token, { version: order.version }); onDone(result.id); return;
    }
    let result: Order;
    if (order) result = await request<Order>(`/orders/${order.id}${requested ? '/changes' : ''}`, context.session.token, { version: order.version, items, expectedTotal: preview.total, ...(requested ? { note } : {}) }, requested ? 'POST' : 'PATCH');
    else {
      const payload = { items, expectedTotal: preview.total, method: selectedGroup?.method ?? method, ...(groupId ? { groupId } : {}) };
      const fingerprint = JSON.stringify(payload);
      const submission = key.current?.payload === fingerprint ? key.current : { payload: fingerprint, key: crypto.randomUUID() };
      key.current = submission;
      result = await request<Order>('/orders', context.session.token, { ...payload, key: submission.key });
    }
    onDone(result.id);
  }, requested ? 'Change request submitted. Accepted items are unchanged until the seller approves.' : order ? 'Order updated. The original hold deadline has not changed.' : 'Order reserved. Submit payment evidence before the deadline.');
  return <><div className="page-title"><span className="eyebrow">{order ? `ORDER ${order.reference}` : 'YOUR CART'}</span><h1>{requested ? 'Request a correction' : order ? 'Edit your unpaid order' : 'Your selection'}</h1><p>{requested ? 'Requests do not reserve replacement stock. The seller checks availability and records any external payment or refund before approval. You may remove every item for a reviewed full refund.' : order ? `Retained items keep accepted prices. Additions use current prices. Your deadline stays ${date(order.deadline)}.` : 'Your cart is not a reservation. Review the current prices, then confirm to start a timed hold.'}</p></div><fieldset disabled={context.busy} className="plain-fieldset"><section className="card"><h2>{order ? 'Desired items' : 'Cart items'}</h2>{choices.length ? <div className="selection-list">{choices.map(product => <div className="selection-row" key={product.id}><div><strong>{product.name}</strong><small>{product.published ? `${money(product.price, context.session.currency)} now · ${product.available} available` : 'No longer published · retained items only'}</small></div><Quantity name={product.name} value={quantities[product.id] ?? 0} max={Math.min(2147483647, product.available + (retained[product.id] ?? 0))} onChange={quantity => update(product.id, quantity)} /></div>)}</div> : <p>No published products are available yet.</p>}{Object.keys(quantities).some(id => quantities[id] > 0 && !choices.some(product => product.id === id)) && <div className="notice warning">Some cart products are no longer published. Remove them before checkout.{Object.keys(quantities).filter(id => quantities[id] > 0 && !choices.some(product => product.id === id)).map(id => <button key={id} onClick={() => update(id, 0)}>Remove unavailable item</button>)}</div>}</section>
    {!order && !groupId && suggestedGroup && <section className="card"><span className="eyebrow">SUGGESTED GROUP</span><h2>Keep your purchases together?</h2><p>Your most recent open group uses <strong>{methodLabel(suggestedGroup.method).toLowerCase()}</strong> and includes {suggestedGroup.orders.map(value => value.reference).join(', ') || 'no orders yet'}. Choose it explicitly, or create a separate group below.</p><button onClick={() => { setGroupId(suggestedGroup.id); setPreview(null); }}>Combine with this open group</button></section>}
    {!order && <section className="card"><h2>Delivery or handover</h2><label className="field">Combine with an existing open group<select value={groupId} onChange={event => { setGroupId(event.target.value); setPreview(null); }}><option value="">Create a new group</option>{openGroups.map(group => <option key={group.id} value={group.id}>{methodLabel(group.method)} · {date(group.created_at)} · {group.orders.length} orders</option>)}</select></label>{selectedGroup ? <div className="notice info"><strong>{methodLabel(selectedGroup.method)} for the whole group</strong><p>This order will share one fulfillment event with {selectedGroup.orders.map(order => order.reference).join(', ') || 'the group’s purchases'}. Each order still needs its own payment.</p></div> : <div className="method-options"><label><input type="radio" name="method" checked={method === 'delivery'} onChange={() => { setMethod('delivery'); setPreview(null); }} />Delivery</label><label><input type="radio" name="method" checked={method === 'in_person'} onChange={() => { setMethod('in_person'); setPreview(null); }} />In-person handover</label></div>}<p className="muted">One method applies to every order in the group. Delivery codes are optional and can be supplied after checkout.</p></section>}
    {requested && <section className="card"><label className="field">Message to the seller (optional)<textarea value={note} onChange={event => setNote(event.target.value)} maxLength={2000} placeholder="Explain the replacement or removal" /></label></section>}
    {preview && <section className="card accepted-preview"><span className="eyebrow">SERVER PRICE PREVIEW</span><h2>{requested ? 'Requested selection' : 'Review before confirming'}</h2><Lines lines={preview.lines} currency={context.session.currency} /><div className="total-row"><span>Total</span><strong>{money(preview.total, context.session.currency)}</strong></div>{order && <p>Difference from current order: <strong>{money(preview.total - order.total, order.currency)}</strong></p>}<p className="muted">{requested ? 'Nothing changes until seller approval. A price change before approval requires a new request.' : `By confirming you accept these prices.${order ? '' : ` Your hold lasts ${context.session.holdMinutes} minutes.`}`}</p><button className="text-button" onClick={() => setPreview(null)}>Change selection / refresh prices</button></section>}
    </fieldset><Primary busy={context.busy} disabled={!order && items.length === 0} onClick={preview ? accept : calculate}>{preview ? requested ? 'Submit change request' : order ? items.length ? 'Accept revised order' : 'Cancel empty order' : 'Accept prices & reserve order' : 'Review current prices'}</Primary></>;
}

export function OrderDetail({ order, products, context, seller, edit }: { order: Order; products: Product[]; context: Workspace; seller: boolean; edit: () => void }) {
  const [staged, setStaged] = useState<string[]>([]);
  const [reason, setReason] = useState('');
  const pending = order.changes.find(change => change.state === 'pending');
  const customerOwns = order.user_id === context.session.user.id;
  const awaiting = order.status === 'awaiting_payment';
  const groupOpen = order.group.state === 'open';
  const uploadFiles = (files: FileList | null) => {
    if (!files?.length) return;
    const selected = Array.from(files);
    void context.run(async () => { for (const file of selected) { const id = await upload(context.session.token, file, 'evidence'); setStaged(current => [...current, id]); } }, 'Screenshots uploaded, but not submitted. Use “Submit evidence for review” before the deadline.');
  };
  const submit = () => void context.run(async () => { await request<Order>(`/orders/${order.id}/evidence`, context.session.token, { version: order.version, mediaIds: staged }); setStaged([]); }, 'Evidence submitted. Your items stay reserved until the seller decides.');
  const decide = (decision: 'confirmed' | 'rejected') => void context.run(async () => {
    if (!window.confirm(decision === 'confirmed' ? `Have you checked the external account and received ${money(order.total, order.currency)} for order ${order.reference}? Screenshots alone do not verify a transfer.` : 'Reject this payment and release the reserved items?')) return false;
    await request(`/seller/orders/${order.id}/payment`, context.session.token, { version: order.version, decision, ...(decision === 'rejected' ? { reason } : {}) });
  });
  return <><div className="page-title"><span className="eyebrow">{seller ? `${order.customer.first_name}${order.customer.username ? ` · @${order.customer.username}` : ''}` : 'YOUR ORDER'}</span><h1>{order.reference}</h1><span className={`badge ${order.status}`}>{statusLabels[order.status]}</span><p>Created {date(order.created_at)}</p></div><section className="card"><h2>Accepted items</h2><Lines lines={order.lines} currency={order.currency} /><div className="total-row"><span>Accepted total</span><strong>{money(order.total, order.currency)}</strong></div><button className="link-row" onClick={() => context.openGroup(order.group_id)}>{methodLabel(order.group.method)} · {order.group.state === 'completed' ? order.group.method === 'delivery' ? 'Sent' : 'Handed over' : order.group.state}<span>View group →</span></button></section>
    {awaiting && <section className="card payment-instructions"><h2>Pay outside the app</h2><p className="large-price">{money(order.total, order.currency)}</p><p>Use reference <strong>{order.reference}</strong>.</p><div className="notice warning"><strong>Submit evidence before {date(order.deadline)}</strong><p>Uploading is not submission. Edits do not extend this deadline.</p></div><p className="preserve">{context.session.paymentInstructions}</p></section>}
    {order.status === 'payment_review' && <div className="notice info"><strong>Waiting for the seller’s payment review</strong><p>The submitted evidence keeps these items reserved until the seller confirms or rejects payment. The original deadline no longer releases them.</p></div>}
    {order.status === 'paid' && <div className="notice success"><strong>Payment confirmed</strong><p>These items are bought. Fulfillment progress is tracked separately in your group.</p></div>}
    {order.status === 'expired' && <div className="notice warning"><strong>The unpaid hold expired</strong><p>Items are no longer reserved. Create a new order at current prices and availability; a late upload cannot revive this order.</p></div>}
    {order.status === 'cancelled' && <div className="notice info">This order was cancelled and its holds released.</div>}
    {order.status === 'payment_rejected' && <div className="notice error"><strong>Payment rejected</strong><p>{order.decision?.reason || 'The seller could not verify payment.'}</p><p>Reservations have been released. You can place a new order from the shop.</p></div>}
    {customerOwns && awaiting && groupOpen && <section className="card"><h2>Your payment screenshots</h2><p>JPEG, PNG or WebP, up to 10 MiB per file. Upload successfully, inspect, then explicitly submit.</p><label className="upload-button">{context.busy ? 'Uploading / working…' : 'Upload payment screenshots'}<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={context.busy} onChange={event => { uploadFiles(event.target.files); event.target.value = ''; }} /></label>{staged.length > 0 && <><div className="evidence-grid">{staged.map((id, index) => <div key={id}><Media id={id} token={context.session.token} alt={`Unsubmitted screenshot ${index + 1}`} /><button disabled={context.busy} onClick={() => setStaged(current => current.filter(item => item !== id))}>Remove screenshot {index + 1}</button></div>)}</div><div className="notice warning">{staged.length} uploaded screenshot(s) · Not submitted yet</div></>}<Primary busy={context.busy} disabled={staged.length === 0} onClick={submit}>Submit evidence for review</Primary><div className="action-row"><button disabled={context.busy} onClick={edit}>Edit unpaid order</button><button className="danger" disabled={context.busy} onClick={() => void context.run(async () => { if (!window.confirm('Cancel this order and release all held items?')) return false; await request(`/orders/${order.id}/cancel`, context.session.token, { version: order.version }); }, 'Order cancelled.')}>Cancel order</button></div></section>}
    {order.evidence.length > 0 && <section className="card"><h2>Submitted payment evidence</h2><p className="muted">Screenshots support review; they do not automatically verify a bank transfer.</p><div className="evidence-grid">{order.evidence.map((evidence, index) => <figure key={evidence.id}><Media id={evidence.media_id} token={context.session.token} alt={`Payment screenshot ${index + 1} for ${order.reference}`} /><figcaption>Submitted {date(evidence.created_at)}<br />Revision {order.revisions.find(revision => revision.id === evidence.revision_id)?.number ?? evidence.revision_id}</figcaption></figure>)}</div></section>}
    {seller && order.status === 'payment_review' && <section className="card"><h2>Verify the external transfer</h2>{pending && <div className="notice warning">A change request is pending. You may confirm payment, but packing remains blocked until the request is resolved.</div>}<label className="field">Reason for rejection<textarea value={reason} disabled={context.busy} maxLength={2000} onChange={event => setReason(event.target.value)} placeholder="Required when rejecting payment" /></label><Primary busy={context.busy} onClick={() => decide('confirmed')}>Confirm payment received</Primary><button className="danger wide" disabled={context.busy || !reason.trim()} onClick={() => decide('rejected')}>Reject payment & release items</button></section>}
    {customerOwns && (order.status === 'payment_review' || order.status === 'paid') && groupOpen && !pending && <section className="card"><h2>Need a change?</h2><p>Request an item correction for seller review. Extra purchases can also be placed as a separate order in an open group.</p><button className="primary wide" disabled={context.busy} onClick={edit}>Request an item change</button></section>}
    {!groupOpen && (order.status === 'paid' || order.status === 'payment_review') && <div className="notice info">{order.group.state === 'packing' ? 'This group is being packed. The seller must reopen it before item or delivery changes.' : 'Fulfillment is complete. This order is kept as read-only history.'}</div>}
    {order.changes.length > 0 && <section className="card"><h2>Change requests & decisions</h2>{order.changes.map(change => <article className="request-history" key={change.id}><div className="row"><strong>{change.state.charAt(0).toUpperCase() + change.state.slice(1)} request</strong><small>{date(change.created_at)}</small></div><p>Requested total: <strong>{money(change.requested_total, order.currency)}</strong></p><ul>{change.selection.map(item => <li key={item.productId}>{products.find(product => product.id === item.productId)?.name ?? order.revisions.flatMap(revision => revision.lines).find(line => line.product_id === item.productId)?.name ?? 'Product no longer in catalog'} × {item.quantity}</li>)}</ul>{change.selection.length === 0 && <p>Full removal of all items</p>}{change.note && <p className="preserve">Customer note: {change.note}</p>}{change.reason && <p className="preserve">Seller reason: {change.reason}</p>}{change.difference !== null && <p>Recorded difference: {money(change.difference, order.currency)}</p>}{change.settlement_note && <p className="preserve">External settlement: {change.settlement_note}</p>}{change.resolved_at && <small>Resolved {date(change.resolved_at)}</small>}{change.state === 'pending' && customerOwns && groupOpen && <button disabled={context.busy} onClick={() => void context.run(async () => { await request(`/orders/${order.id}/changes/${change.id}/withdraw`, context.session.token, { version: order.version }); }, 'Change request withdrawn.')}>Withdraw request</button>}{change.state === 'pending' && seller && <ChangeReview order={order} change={change} products={products} context={context} />}</article>)}</section>}
    <section className="card"><h2>Accepted revision history</h2>{order.revisions.map(revision => <details key={revision.id}><summary>Revision {revision.number} · {money(revision.total, order.currency)} · {date(revision.created_at)}{revision.id === order.current_revision ? ' · Current' : ''}</summary><Lines lines={revision.lines} currency={order.currency} /></details>)}{order.decision && <p>Payment decision: {order.decision.decision}{order.decision.reason ? ` · ${order.decision.reason}` : ''}{order.decision.created_at ? ` · ${date(order.decision.created_at)}` : ''}</p>}</section></>;
}

export function GroupDetail({ group, context, seller }: { group: Group; context: Workspace; seller: boolean }) {
  const [method, setMethod] = useState(group.method);
  const [code, setCode] = useState(group.delivery_code ?? '');
  const [dirty, setDirty] = useState(false);
  const [formVersion, setFormVersion] = useState(group.version);
  useEffect(() => {
    if (!dirty) { setMethod(group.method); setCode(group.delivery_code ?? ''); setFormVersion(group.version); }
  }, [group.version, group.method, group.delivery_code, dirty]);
  const pending = group.orders.some(order => order.changes.some(change => change.state === 'pending'));
  const paidUnits = group.packing_lines.reduce((sum, line) => sum + line.quantity, 0);
  const unpaid = group.orders.filter(order => order.status !== 'paid');
  const save = () => void context.run(async () => { await request(`/groups/${group.id}`, context.session.token, { version: formVersion, method, deliveryCode: method === 'delivery' ? code.trim() || null : null }, 'PATCH'); setDirty(false); }, 'Fulfillment details saved for the whole group.');
  const pack = () => void context.run(async () => {
    if (!window.confirm(`Start packing ${paidUnits} paid item(s)?${unpaid.length ? ` ${unpaid.length} unpaid or terminal order(s) will move to a new open group without copying this delivery code.` : ''} Customer changes will be frozen.`)) return false;
    await request(`/seller/groups/${group.id}/pack`, context.session.token, { version: group.version });
  }, 'Packing started. Any nonpaid orders are now in a separate open group.');
  const complete = () => void context.run(async () => {
    const missing = group.method === 'delivery' && !group.delivery_code;
    if (!window.confirm(missing ? 'No delivery code was supplied. Confirm you have sent this entire paid group anyway? This completes fulfillment without changing payment or stock.' : `Mark this entire paid group ${group.method === 'delivery' ? 'sent' : 'handed over'}? This completes fulfillment without changing payment or stock.`)) return false;
    await request(`/seller/groups/${group.id}/complete`, context.session.token, { version: group.version, allowMissingCode: missing });
  }, group.method === 'delivery' ? 'Group marked sent.' : 'Group marked handed over.');
  return <><div className="page-title"><span className="eyebrow">{seller ? group.customer.first_name + (group.customer.username ? ` · @${group.customer.username}` : '') : 'YOUR FULFILLMENT GROUP'}</span><h1>{methodLabel(group.method)}</h1><span className={`badge ${group.state}`}>{group.state === 'completed' ? group.completion_kind === 'sent' ? 'Sent' : 'Handed over' : group.state === 'packing' ? 'Being packed' : 'Open for additions'}</span><p>Created {date(group.created_at)}{group.completed_at && ` · Completed ${date(group.completed_at)}`}</p></div><section className="card"><h2>Whole-group details</h2><p>Every order in this group shares one {group.method === 'delivery' ? 'delivery' : 'in-person handover'}. Payment is still per order.</p>{group.method === 'delivery' && <div className={`notice ${group.delivery_code ? 'info' : 'warning'}`}><strong>{group.delivery_code ? 'Customer-provided delivery code' : 'No delivery code supplied'}</strong><p className="preserve">{group.delivery_code || 'A code is optional. Missing delivery information does not change paid status.'}</p></div>}{!seller && group.state === 'open' && <fieldset disabled={context.busy} className="plain-fieldset"><label className="field">Method for all orders<select value={method} onChange={event => { setMethod(event.target.value as Method); setCode(''); setDirty(true); }}><option value="delivery">Delivery</option><option value="in_person">In-person handover</option></select></label>{method === 'delivery' && <label className="field">Optional delivery code<input value={code} onChange={event => { setCode(event.target.value); setDirty(true); }} maxLength={200} placeholder="Create a shipment request externally, then paste its code" /><small>This is plain text, not a verified shipment or carrier integration.</small></label>}{dirty && formVersion !== group.version && <div className="notice warning"><strong>This group changed while you were editing</strong><p>Reload its current details before making a new change. Unsaved method and code edits will be discarded.</p><button onClick={() => setDirty(false)}>Reload current group details</button></div>}<Primary busy={context.busy} disabled={dirty && formVersion !== group.version} onClick={save}>Save whole-group details</Primary>{method === 'in_person' && group.delivery_code && <p className="muted">Saving in-person handover clears the delivery code. Switching back requires entering a new code.</p>}</fieldset>}{group.state !== 'open' && <p className="muted">{group.state === 'packing' ? 'Contents and delivery details are frozen. Ask the seller to reopen this group if changes are needed.' : 'This completed group is read-only. New purchases use an open or new group.'}</p>}</section>
    <section className="card"><h2>{group.state === 'completed' ? 'Fulfilled contents' : 'Paid packing contents'}</h2><Lines lines={group.packing_lines} currency={context.session.currency} /><p className="muted">{paidUnits} paid item(s). Unpaid and review-held items are not included.</p>{pending && <div className="notice warning">Pending item requests must be resolved before packing or completion.</div>}</section><section className="card"><h2>Associated orders</h2><div className="stack">{group.orders.map(order => <OrderCard key={order.id} order={order} onClick={() => context.openOrder(order.id)} />)}</div>{unpaid.length > 0 && <p className="muted">{unpaid.length} nonpaid order(s) are excluded from the paid packing list. Starting paid-only packing moves them to a new open group, keeping payment and reservation history intact.</p>}</section>
    {seller && group.state === 'open' && <Primary busy={context.busy} disabled={pending || paidUnits === 0} onClick={pack}>Start paid-only packing</Primary>}
    {seller && group.state === 'packing' && <section className="card"><h2>Finish this group</h2><Primary busy={context.busy} disabled={pending || paidUnits === 0} onClick={complete}>{group.method === 'delivery' ? 'Mark whole group sent' : 'Mark whole group handed over'}</Primary><button className="wide" disabled={context.busy} onClick={() => void context.run(async () => { if (!window.confirm('Reopen this group and allow customer changes? The current packing list will need to be checked again.')) return false; await request(`/seller/groups/${group.id}/reopen`, context.session.token, { version: group.version }); }, 'Group reopened. Check the refreshed packing contents before packing again.')}>Reopen for changes</button></section>}
  </>;
}
