import { useEffect, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { aggregate, request, upload, type Change, type Group, type Method, type Order, type Preview, type Product, type Selection } from './api';
import { date, money } from './i18n/format';
import { methodLabel, statusLabel } from './i18n/labels';
import { Empty, Gallery, Lines, Media, OrderCard, Primary, Quantity, type Workspace } from './ui';
import { ChangeReview } from './seller';

const CHANGE_STATE_KEYS = {
  pending: 'customer.order.changeState.pending',
  approved: 'customer.order.changeState.approved',
  rejected: 'customer.order.changeState.rejected',
  withdrawn: 'customer.order.changeState.withdrawn',
} as const satisfies Record<Change['state'], string>;

const DECISION_KEYS = {
  confirmed: 'customer.order.decisionConfirmed',
  rejected: 'customer.order.decisionRejected',
} as const;

export function Catalog({ products, context, open }: { products: Product[]; context: Workspace; open: (id: string) => void }) {
  const { t } = useTranslation();
  return <><div className="page-title"><span className="eyebrow">{t('customer.catalog.eyebrow')}</span><h1>{t('customer.catalog.title')}</h1><p>{t('customer.catalog.intro')}</p></div>{products.length ? <div className="product-grid">{products.map(product => <article className="product-card" key={product.id}><button className="product-image" onClick={() => open(product.id)} aria-label={t('customer.catalog.viewProduct', { name: product.name })}><img src={`/api/public-media/${product.images[0]}`} alt={product.name} loading="lazy" /></button><div className="product-copy"><button className="product-name" onClick={() => open(product.id)}>{product.name}</button><strong>{money(product.price, context.session.currency)}</strong><p className={product.available === 0 ? 'stock unavailable' : 'stock'}>{product.available > 0 ? t('customer.catalog.availableCount', { count: product.available }) : product.reserved > 0 ? t('customer.catalog.temporarilyReserved') : t('customer.catalog.soldOut')}</p><small>{t('customer.catalog.stockCounts', { reserved: product.reserved, bought: product.bought })}</small></div></article>)}</div> : <Empty title={t('customer.catalog.emptyTitle')}>{t('customer.catalog.emptyBody')}</Empty>}</>;
}
export function ProductDetail({ product, context, quantity, setQuantity }: { product: Product; context: Workspace; quantity: number; setQuantity: (value: number) => void }) {
  const { t } = useTranslation();
  const [selected, setSelected] = useState(Math.min(Math.max(quantity, 1), product.available));
  const [added, setAdded] = useState(false);
  return <><Gallery ids={product.images} token={context.session.token} name={product.name} publicImages /><div className="page-title"><span className="eyebrow">{t('customer.product.eyebrow')}</span><h1>{product.name}</h1><div className="large-price">{money(product.price, context.session.currency)}</div>{product.comment && <p className="preserve">{product.comment}</p>}</div><div className="stock-summary"><div><strong>{product.available}</strong><span>{t('customer.product.available')}</span></div><div><strong>{product.reserved}</strong><span>{t('customer.product.reserved')}</span></div><div><strong>{product.bought}</strong><span>{t('customer.product.bought')}</span></div></div><section className="card"><div className="row"><label>{t('customer.product.quantityLabel')}</label><Quantity name={product.name} value={selected} max={product.available} onChange={value => { setSelected(value); setAdded(false); }} /></div><p className="muted">{t('customer.product.note')}</p><Primary busy={context.busy} disabled={selected === 0 || selected > product.available} onClick={() => { setQuantity(selected); setAdded(true); }}>{quantity ? t('customer.product.updateCart') : t('customer.product.addToCart')}</Primary>{added && <p className="success-text" role="status">{t('customer.product.cartUpdated')}</p>}</section></>;
}

export function SelectionEditor({ products, context, initial, order, checkoutKey, onSelection, onDone }: { products: Product[]; context: Workspace; initial?: Record<string, number>; order?: Order; checkoutKey?: { current: { payload: string; key: string } | null }; onSelection?: (value: Record<string, number>) => void; onDone: (id: string) => void }) {
  const { t } = useTranslation();
  const [quantities, setQuantities] = useState<Record<string, number>>(initial ?? Object.fromEntries(aggregate(order?.lines ?? []).map(item => [item.productId, item.quantity])));
  const [preview, setPreview] = useState<Preview | null>(null);
  const [note, setNote] = useState('');
  const localKey = useRef<{ payload: string; key: string } | null>(null);
  const key = checkoutKey ?? localKey;
  const requested = !!order && order.status !== 'awaiting_payment';
  const items: Selection = Object.entries(quantities).filter(([, quantity]) => quantity > 0).map(([productId, quantity]) => ({ productId, quantity }));
  const choices = [...products.filter(product => product.published), ...aggregate(order?.lines ?? []).filter(item => !products.some(product => product.id === item.productId)).map(item => ({ id: item.productId, name: order!.lines.find(line => line.product_id === item.productId)!.name, price: 0, available: 0, published: false }))];
  const update = (id: string, quantity: number) => {
    const next = { ...quantities, [id]: quantity }; setQuantities(next); setPreview(null); onSelection?.(next);
  };
  const retained = Object.fromEntries(aggregate(order?.lines ?? []).map(item => [item.productId, item.quantity]));
  const calculate = () => void context.run(async () => { setPreview(await request<Preview>('/orders/preview', context.session.token, { items, ...(order ? { orderId: order.id } : {}) })); });
  const accept = () => void context.run(async () => {
    if (!preview) return;
    if (order && !requested && items.length === 0) {
      if (!window.confirm(t('customer.selection.cancelUnpaidPrompt'))) return false;
      const result = await request<Order>(`/orders/${order.id}/cancel`, context.session.token, { version: order.version }); onDone(result.id); return;
    }
    let result: Order;
    if (order) result = await request<Order>(`/orders/${order.id}${requested ? '/changes' : ''}`, context.session.token, { version: order.version, items, expectedTotal: preview.total, ...(requested ? { note } : {}) }, requested ? 'POST' : 'PATCH');
    else {
      const payload = { items, expectedTotal: preview.total };
      const fingerprint = JSON.stringify(payload);
      const submission = key.current?.payload === fingerprint ? key.current : { payload: fingerprint, key: crypto.randomUUID() };
      key.current = submission;
      result = await request<Order>('/orders', context.session.token, { ...payload, key: submission.key });
    }
    onDone(result.id);
  }, requested ? t('customer.selection.noticeChangeRequest') : order ? t('customer.selection.noticeOrderUpdated') : t('customer.selection.noticeOrderReserved'));
  return <><div className="page-title"><span className="eyebrow">{order ? t('customer.selection.orderEyebrow', { reference: order.reference }) : t('customer.selection.yourCart')}</span><h1>{requested ? t('customer.selection.titleRequest') : order ? t('customer.selection.titleEditOrder') : t('customer.selection.titleSelection')}</h1><p>{requested ? t('customer.selection.introRequest') : order ? t('customer.selection.introOrder', { deadline: date(order.deadline) }) : t('customer.selection.introCart')}</p></div><fieldset disabled={context.busy} className="plain-fieldset"><section className="card"><h2>{order ? t('customer.selection.desiredItems') : t('customer.selection.cartItems')}</h2>{choices.length ? <div className="selection-list">{choices.map(product => <div className="selection-row" key={product.id}><div><strong>{product.name}</strong><small>{product.published ? t('customer.selection.priceNow', { price: money(product.price, context.session.currency), count: product.available }) : t('customer.selection.unavailableItem')}</small></div><Quantity name={product.name} value={quantities[product.id] ?? 0} max={Math.min(2147483647, product.available + (retained[product.id] ?? 0))} onChange={quantity => update(product.id, quantity)} /></div>)}</div> : <p>{t('customer.selection.noPublished')}</p>}{Object.keys(quantities).some(id => quantities[id] > 0 && !choices.some(product => product.id === id)) && <div className="notice warning">{t('customer.selection.unpublishedWarning')}{Object.keys(quantities).filter(id => quantities[id] > 0 && !choices.some(product => product.id === id)).map(id => <button key={id} onClick={() => update(id, 0)}>{t('customer.selection.removeUnavailable')}</button>)}</div>}</section>
    {!order && <section className="card"><h2>{t('customer.selection.fulfillmentTitle')}</h2><p>{t('customer.selection.fulfillmentBody')}</p></section>}
    {requested && <section className="card"><label className="field">{t('customer.selection.messageLabel')}<textarea value={note} onChange={event => setNote(event.target.value)} maxLength={2000} placeholder={t('customer.selection.messagePlaceholder')} /></label></section>}
    {preview && <section className="card accepted-preview"><span className="eyebrow">{t('customer.selection.previewEyebrow')}</span><h2>{requested ? t('customer.selection.previewRequested') : t('customer.selection.previewReview')}</h2><Lines lines={preview.lines} currency={context.session.currency} /><div className="total-row"><span>{t('customer.selection.total')}</span><strong>{money(preview.total, context.session.currency)}</strong></div>{order && <p>{t('customer.selection.differenceFromOrder')} <strong>{money(preview.total - order.total, order.currency)}</strong></p>}<p className="muted">{requested ? t('customer.selection.previewNoteRequest') : order ? t('customer.selection.confirmNote') : t('customer.selection.confirmNoteHold', { count: context.session.holdMinutes })}</p><button className="text-button" onClick={() => setPreview(null)}>{t('customer.selection.changeSelection')}</button></section>}
    </fieldset><Primary busy={context.busy} disabled={!order && items.length === 0} onClick={preview ? accept : calculate}>{preview ? requested ? t('customer.selection.submitChangeRequest') : order ? items.length ? t('customer.selection.acceptRevisedOrder') : t('customer.selection.cancelEmptyOrder') : t('customer.selection.acceptPricesReserve') : t('customer.selection.reviewPrices')}</Primary></>;
}

export function OrderDetail({ order, products, context, seller, edit }: { order: Order; products: Product[]; context: Workspace; seller: boolean; edit: () => void }) {
  const { t } = useTranslation();
  const [staged, setStaged] = useState<string[]>([]);
  const [reason, setReason] = useState('');
  const pending = order.changes.find(change => change.state === 'pending');
  const customerOwns = order.user_id === context.session.user.id;
  const awaiting = order.status === 'awaiting_payment';
  const groupOpen = order.group.state === 'open';
  const uploadFiles = (files: FileList | null) => {
    if (!files?.length) return;
    const selected = Array.from(files);
    void context.run(async () => { for (const file of selected) { const id = await upload(context.session.token, file, 'evidence'); setStaged(current => [...current, id]); } }, t('customer.order.uploadedNotice'));
  };
  const submit = () => void context.run(async () => { await request<Order>(`/orders/${order.id}/evidence`, context.session.token, { version: order.version, mediaIds: staged }); setStaged([]); }, t('customer.order.submitEvidenceNotice'));
  const decide = (decision: 'confirmed' | 'rejected') => void context.run(async () => {
    if (!window.confirm(decision === 'confirmed' ? t('customer.order.confirmDecision', { amount: money(order.total, order.currency), reference: order.reference }) : t('customer.order.rejectPrompt'))) return false;
    await request(`/seller/orders/${order.id}/payment`, context.session.token, { version: order.version, decision, ...(decision === 'rejected' ? { reason } : {}) });
  });
  return <><div className="page-title"><span className="eyebrow">{seller ? `${order.customer.first_name}${order.customer.username ? ` · @${order.customer.username}` : ''}` : t('customer.order.yourOrder')}</span><h1>{order.reference}</h1><span className={`badge ${order.status}`}>{statusLabel(order.status)}</span><p>{t('customer.order.created', { date: date(order.created_at) })}</p></div><section className="card"><h2>{t('customer.order.acceptedItems')}</h2><Lines lines={order.lines} currency={order.currency} /><div className="total-row"><span>{t('customer.order.acceptedTotal')}</span><strong>{money(order.total, order.currency)}</strong></div><button className="link-row" onClick={() => context.openGroup(order.group_id)}>{t('customer.order.packageState', { method: methodLabel(order.group.method), state: order.group.state === 'completed' ? order.group.method === 'delivery' ? t('customer.order.packageSent') : t('customer.order.packageHandedOver') : t('customer.order.packageOpen') })}<span>{t('customer.order.viewPackage')}</span></button></section>
    {awaiting && <section className="card payment-instructions"><h2>{t('customer.order.payOutside')}</h2><p className="large-price">{money(order.total, order.currency)}</p><p>{t('customer.order.useReference')} <strong>{order.reference}</strong>.</p><div className="notice warning"><strong>{t('customer.order.submitBefore', { date: date(order.deadline) })}</strong><p>{t('customer.order.uploadNote')}</p></div><p className="preserve">{context.session.paymentInstructions}</p></section>}
    {order.status === 'payment_review' && <div className="notice info"><strong>{t('customer.order.reviewTitle')}</strong><p>{t('customer.order.reviewBody')}</p></div>}
    {order.status === 'paid' && <div className="notice success"><strong>{t('customer.order.paidTitle')}</strong><p>{t('customer.order.paidBody')}</p></div>}
    {order.status === 'expired' && <div className="notice warning"><strong>{t('customer.order.expiredTitle')}</strong><p>{t('customer.order.expiredBody')}</p></div>}
    {order.status === 'cancelled' && <div className="notice info">{t('customer.order.cancelledNotice')}</div>}
    {order.status === 'payment_rejected' && <div className="notice error"><strong>{t('customer.order.rejectedTitle')}</strong><p>{order.decision?.reason || t('customer.order.rejectedFallback')}</p><p>{t('customer.order.rejectedBody')}</p></div>}
    {customerOwns && awaiting && groupOpen && <section className="card"><h2>{t('customer.order.screenshotsTitle')}</h2><p>{t('customer.order.screenshotsNote')}</p><label className="upload-button">{context.busy ? t('customer.order.uploading') : t('customer.order.uploadEvidence')}<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={context.busy} onChange={event => { uploadFiles(event.target.files); event.target.value = ''; }} /></label>{staged.length > 0 && <><div className="evidence-grid">{staged.map((id, index) => <div key={id}><Media id={id} token={context.session.token} alt={t('customer.order.unsubmittedAlt', { number: index + 1 })} /><button disabled={context.busy} onClick={() => setStaged(current => current.filter(item => item !== id))}>{t('customer.order.removeScreenshot', { number: index + 1 })}</button></div>)}</div><div className="notice warning">{t('customer.order.uploadedScreenshots', { count: staged.length })}</div></>}<Primary busy={context.busy} disabled={staged.length === 0} onClick={submit}>{t('customer.order.submitEvidence')}</Primary><div className="action-row"><button disabled={context.busy} onClick={edit}>{t('customer.order.editUnpaidOrder')}</button><button className="danger" disabled={context.busy} onClick={() => void context.run(async () => { if (!window.confirm(t('customer.order.cancelPrompt'))) return false; await request(`/orders/${order.id}/cancel`, context.session.token, { version: order.version }); }, t('customer.order.cancelNotice'))}>{t('customer.order.cancelOrder')}</button></div></section>}
    {order.evidence.length > 0 && <section className="card"><h2>{t('customer.order.evidenceTitle')}</h2><p className="muted">{t('customer.order.evidenceNote')}</p><div className="evidence-grid">{order.evidence.map((evidence, index) => <figure key={evidence.id}><Media id={evidence.media_id} token={context.session.token} alt={t('customer.order.evidenceAlt', { number: index + 1, reference: order.reference })} /><figcaption>{t('customer.order.evidenceSubmitted', { date: date(evidence.created_at) })}<br />{t('customer.order.evidenceRevision', { number: order.revisions.find(revision => revision.id === evidence.revision_id)?.number ?? evidence.revision_id })}</figcaption></figure>)}</div></section>}
    {seller && order.status === 'payment_review' && <section className="card"><h2>{t('customer.order.verifyTitle')}</h2>{pending && <div className="notice warning">{t('customer.order.pendingNotice')}</div>}<label className="field">{t('customer.order.rejectReason')}<textarea value={reason} disabled={context.busy} maxLength={2000} onChange={event => setReason(event.target.value)} placeholder={t('customer.order.rejectPlaceholder')} /></label><Primary busy={context.busy} onClick={() => decide('confirmed')}>{t('customer.order.confirmReceived')}</Primary><button className="danger wide" disabled={context.busy || !reason.trim()} onClick={() => decide('rejected')}>{t('customer.order.rejectRelease')}</button></section>}
    {customerOwns && (order.status === 'payment_review' || order.status === 'paid') && groupOpen && !pending && <section className="card"><h2>{t('customer.order.needChangeTitle')}</h2><p>{t('customer.order.needChangeBody')}</p><button className="primary wide" disabled={context.busy} onClick={edit}>{t('customer.order.requestChange')}</button></section>}
    {!groupOpen && (order.status === 'paid' || order.status === 'payment_review') && <div className="notice info">{t('customer.order.readOnlyNotice')}</div>}
    {order.changes.length > 0 && <section className="card"><h2>{t('customer.order.changesTitle')}</h2>{order.changes.map(change => <article className="request-history" key={change.id}><div className="row"><strong>{t('customer.order.changeRequestTitle', { state: t(CHANGE_STATE_KEYS[change.state]) })}</strong><small>{date(change.created_at)}</small></div><p>{t('customer.order.requestedTotal')} <strong>{money(change.requested_total, order.currency)}</strong></p><ul>{change.selection.map(item => <li key={item.productId}>{t('customer.order.itemLine', { name: products.find(product => product.id === item.productId)?.name ?? order.revisions.flatMap(revision => revision.lines).find(line => line.product_id === item.productId)?.name ?? t('customer.order.productMissing'), quantity: item.quantity })}</li>)}</ul>{change.selection.length === 0 && <p>{t('customer.order.fullRemoval')}</p>}{change.note && <p className="preserve">{t('customer.order.customerNote', { note: change.note })}</p>}{change.reason && <p className="preserve">{t('customer.order.sellerReason', { reason: change.reason })}</p>}{change.difference !== null && <p>{t('customer.order.recordedDifference', { amount: money(change.difference, order.currency) })}</p>}{change.settlement_note && <p className="preserve">{t('customer.order.externalSettlement', { note: change.settlement_note })}</p>}{change.resolved_at && <small>{t('customer.order.resolved', { date: date(change.resolved_at) })}</small>}{change.state === 'pending' && customerOwns && groupOpen && <button disabled={context.busy} onClick={() => void context.run(async () => { await request(`/orders/${order.id}/changes/${change.id}/withdraw`, context.session.token, { version: order.version }); }, t('customer.order.withdrawnNotice'))}>{t('customer.order.withdraw')}</button>}{change.state === 'pending' && seller && <ChangeReview order={order} change={change} products={products} context={context} />}</article>)}</section>}
    <section className="card"><h2>{t('customer.order.revisionHistory')}</h2>{order.revisions.map(revision => <details key={revision.id}><summary>{t('customer.order.revisionSummary', { number: revision.number, total: money(revision.total, order.currency), date: date(revision.created_at) })}{revision.id === order.current_revision ? t('customer.order.currentMark') : ''}</summary><Lines lines={revision.lines} currency={order.currency} /></details>)}{order.decision && <p>{t('customer.order.paymentDecision')} {order.decision.decision in DECISION_KEYS ? t(DECISION_KEYS[order.decision.decision as keyof typeof DECISION_KEYS]) : order.decision.decision}{order.decision.reason ? t('customer.order.decisionReason', { reason: order.decision.reason }) : ''}{order.decision.created_at ? t('customer.order.decisionDate', { date: date(order.decision.created_at) }) : ''}</p>}</section></>;
}

export function GroupDetail({ group, context, seller }: { group: Group; context: Workspace; seller: boolean }) {
  const { t } = useTranslation();
  const [method, setMethod] = useState<Method>('delivery');
  const [code, setCode] = useState(group.delivery_code ?? '');
  const [dirty, setDirty] = useState(false);
  const [formVersion, setFormVersion] = useState(group.version);
  useEffect(() => {
    if (!dirty) { setCode(group.delivery_code ?? ''); setFormVersion(group.version); }
  }, [group.version, group.delivery_code, dirty]);
  const pending = group.orders.some(order => order.changes.some(change => change.state === 'pending'));
  const paidUnits = group.packing_lines.reduce((sum, line) => sum + line.quantity, 0);
  const unpaid = group.orders.filter(order => order.status !== 'paid');
  const stale = dirty && formVersion !== group.version;
  const saveCode = () => void context.run(async () => { await request(`/groups/${group.id}`, context.session.token, { version: formVersion, deliveryCode: code.trim() || null }, 'PATCH'); setDirty(false); }, t('customer.group.codeSaved'));
  const ship = () => void context.run(async () => {
    const missing = method === 'delivery' && !code.trim();
    const remaining = unpaid.length ? t('customer.group.shipRemaining', { count: unpaid.length }) : '';
    if (!window.confirm(t('customer.group.shipConfirm', { paid: t('customer.group.paidItems', { count: paidUnits }), method: t(method === 'delivery' ? 'customer.group.asDelivery' : 'customer.group.asHandover'), remaining, warning: missing ? t('customer.group.shipMissingCode') : '' }))) return false;
    await request(`/seller/groups/${group.id}/ship`, context.session.token, { version: group.version, method, ...(code.trim() ? { deliveryCode: code.trim() } : {}), ...(missing ? { allowMissingCode: true } : {}) });
  }, t('customer.group.shippedNotice'));
  return <><div className="page-title"><span className="eyebrow">{seller ? group.customer.first_name + (group.customer.username ? ` · @${group.customer.username}` : '') : t('customer.group.yourPackage')}</span><h1>{group.state === 'completed' ? methodLabel(group.method) : t('customer.group.package')}</h1><span className={`badge ${group.state}`}>{group.state === 'completed' ? group.completion_kind === 'sent' ? t('customer.group.packageSent') : t('customer.group.packageHandedOver') : t('customer.group.openForAdditions')}</span><p>{t('customer.group.created', { date: date(group.created_at) })}{group.completed_at && t('customer.group.shipped', { date: date(group.completed_at) })}</p></div><section className="card"><h2>{t('customer.group.detailsTitle')}</h2>{group.state === 'completed' ? <><p>{t('customer.group.shippedAs')} <strong>{methodLabel(group.method).toLowerCase()}</strong>.</p>{group.method === 'delivery' && <div className="notice info"><strong>{t('customer.group.deliveryCode')}</strong><p className="preserve">{group.delivery_code || t('customer.group.noRecordedCode')}</p></div>}</> : <><p>{t('customer.group.openNote')}</p>{seller ? <fieldset disabled={context.busy} className="plain-fieldset"><label className="field">{t('customer.group.shipAsLabel')}<select value={method} onChange={event => setMethod(event.target.value as Method)}><option value="delivery">{t('customer.group.deliveryOption')}</option><option value="in_person">{t('customer.group.inPersonOption')}</option></select></label>{method === 'delivery' && <label className="field">{t('customer.group.optionalCodeLabel')}<input value={code} onChange={event => setCode(event.target.value)} maxLength={200} placeholder={t('customer.group.sellerCodePlaceholder')} /></label>}</fieldset> : <><fieldset disabled={context.busy} className="plain-fieldset"><label className="field">{t('customer.group.optionalCodeLabel')}<input value={code} onChange={event => { setCode(event.target.value); setDirty(true); }} maxLength={200} placeholder={t('customer.group.customerCodePlaceholder')} /><small>{t('customer.group.oneCodeNote')}</small></label></fieldset><div className={`notice ${group.delivery_code ? 'info' : 'warning'}`}><strong>{group.delivery_code ? t('customer.group.sharedCode') : t('customer.group.noCodeSupplied')}</strong><p className="preserve">{group.delivery_code || t('customer.group.codeOptionalNote')}</p></div>{stale && <div className="notice warning"><strong>{t('customer.group.staleTitle')}</strong><p>{t('customer.group.staleBody')}</p><button onClick={() => setDirty(false)}>{t('customer.group.reload')}</button></div>}<Primary busy={context.busy} disabled={stale} onClick={saveCode}>{t('customer.group.saveCode')}</Primary></>}</>}</section>
    <section className="card"><h2>{group.state === 'completed' ? t('customer.group.shippedContents') : t('customer.group.paidContents')}</h2><Lines lines={group.packing_lines} currency={context.session.currency} /><p className="muted">{t('customer.group.paidItemsIncluded', { count: paidUnits })}</p>{pending && <div className="notice warning">{t('customer.group.pendingResolve')}</div>}</section><section className="card"><h2>{t('customer.group.associatedOrders')}</h2><div className="stack">{group.orders.map(order => <OrderCard key={order.id} order={order} onClick={() => context.openOrder(order.id)} />)}</div>{unpaid.length > 0 && <p className="muted">{t('customer.group.nonpaidOrders', { count: unpaid.length })}</p>}</section>
    {seller && group.state === 'open' && <Primary busy={context.busy} disabled={pending || paidUnits === 0} onClick={ship}>{t('customer.group.shipAllPaid', { count: paidUnits })}</Primary>}
    {group.state === 'completed' && <p className="muted">{t('customer.group.readOnly')}</p>}
  </>;
}
